/*
 * Godot C-ABI adapter for the GraalVM-compiled Minecraft input surface.
 * The Java layer does not know about Godot. This adapter owns the GDExtension
 * ABI and forwards plain integer touch data to the Java Native Image library.
 */
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "gdextension_interface.h"
#include "minecraft_java.h" /* generated by build.sh from native-image output */

#if defined(_WIN32)
#define GDEXTENSION_EXPORT __declspec(dllexport)
#else
#define GDEXTENSION_EXPORT __attribute__((visibility("default")))
#endif

#define CLASS_NAME "MinecraftTouch"
#define PARENT_CLASS_NAME "RefCounted"

/* gdextension_interface.h returns a generic function pointer. The Godot API
 * explicitly permits an intermediate void-pointer cast for typed interfaces. */
#define LOAD_GODOT_INTERFACE(type, name) ((type)(void *)get_proc_address(name))

typedef struct {
    int placeholder;
} MinecraftTouchInstance;

static GDExtensionInterfaceGetProcAddress godot_get_proc_address;
static GDExtensionClassLibraryPtr godot_library;
static GDExtensionInterfaceStringNameNewWithUtf8Chars string_name_new;
static GDExtensionInterfaceClassdbConstructObject classdb_construct_object;
static GDExtensionInterfaceObjectSetInstance object_set_instance;
static GDExtensionInterfaceClassdbRegisterExtensionClass classdb_register_extension_class;
static GDExtensionInterfaceClassdbRegisterExtensionClassMethod classdb_register_extension_class_method;
static GDExtensionInterfaceGetVariantToTypeConstructor variant_to_int;
static GDExtensionInterfaceGetVariantFromTypeConstructor variant_from_int;
static GDExtensionInterfaceVariantNewNil variant_new_nil;

static graal_isolate_t *java_isolate;
static graal_isolatethread_t *java_main_thread;

static GDExtensionStringNamePtr make_string_name(const char *text) {
    GDExtensionStringNamePtr name = NULL;
    string_name_new(&name, text);
    return name;
}

/* Godot interns StringNames created through the C ABI. They are kept for the
 * process lifetime so all names used by this small extension are created once
 * per registration/lifetime and intentionally not freed here. */
static void free_string_name(GDExtensionStringNamePtr name) {
    (void)name;
}

static graal_isolatethread_t *java_thread(void) {
    if (java_isolate == NULL) {
        return NULL;
    }
    graal_isolatethread_t *thread = graal_get_current_thread(java_isolate);
    if (thread == NULL && graal_attach_thread(java_isolate, &thread) != 0) {
        return NULL;
    }
    return thread;
}

static int java_start(void) {
    if (java_isolate != NULL) {
        return 1;
    }
    if (graal_create_isolate(NULL, &java_isolate, &java_main_thread) != 0) {
        java_isolate = NULL;
        java_main_thread = NULL;
        return 0;
    }
    minecraft_bootstrap(java_main_thread);
    return 1;
}

static void set_call_ok(GDExtensionCallError *error) {
    if (error != NULL) {
        error->error = GDEXTENSION_CALL_OK;
        error->argument = 0;
        error->expected = 0;
    }
}

static void set_argument_error(GDExtensionCallError *error, int argument, int expected) {
    if (error != NULL) {
        error->error = GDEXTENSION_CALL_ERROR_INVALID_ARGUMENT;
        error->argument = argument;
        error->expected = expected;
    }
}

static int64_t variant_int(GDExtensionConstVariantPtr value) {
    int64_t result = 0;
    GDExtensionTypeFromVariantConstructorFunc converter =
            variant_to_int(GDEXTENSION_VARIANT_TYPE_INT);
    converter(&result, (GDExtensionVariantPtr)value);
    return result;
}

static void return_int(GDExtensionVariantPtr result, int64_t value) {
    GDExtensionVariantFromTypeConstructorFunc constructor =
            variant_from_int(GDEXTENSION_VARIANT_TYPE_INT);
    constructor(result, &value);
}

static void return_nil(GDExtensionVariantPtr result) {
    variant_new_nil(result);
}

static GDExtensionObjectPtr minecraft_touch_create(void *class_userdata) {
    (void)class_userdata;
    GDExtensionStringNamePtr class_name = make_string_name(CLASS_NAME);
    GDExtensionObjectPtr object = classdb_construct_object(class_name);
    MinecraftTouchInstance *instance = calloc(1, sizeof(*instance));
    if (object != NULL && instance != NULL) {
        object_set_instance(object, class_name, instance);
    } else {
        free(instance);
    }
    free_string_name(class_name);
    return object;
}

static void minecraft_touch_free(void *class_userdata, GDExtensionClassInstancePtr instance) {
    (void)class_userdata;
    free(instance);
}

static void method_touch_down(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    if (argument_count != 5) {
        set_argument_error(error, (int)argument_count, 5);
        return_nil(result);
        return;
    }
    graal_isolatethread_t *thread = java_thread();
    if (thread != NULL) {
        minecraft_touch_down(thread, (int)variant_int(args[0]), (int)variant_int(args[1]),
                (int)variant_int(args[2]), (int)variant_int(args[3]), (int)variant_int(args[4]));
    }
    set_call_ok(error);
    return_nil(result);
}

static void method_touch_move(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    if (argument_count != 5) {
        set_argument_error(error, (int)argument_count, 5);
        return_nil(result);
        return;
    }
    graal_isolatethread_t *thread = java_thread();
    if (thread != NULL) {
        minecraft_touch_move(thread, (int)variant_int(args[0]), (int)variant_int(args[1]),
                (int)variant_int(args[2]), (int)variant_int(args[3]), (int)variant_int(args[4]));
    }
    set_call_ok(error);
    return_nil(result);
}

static void method_touch_up(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    if (argument_count != 1) {
        set_argument_error(error, (int)argument_count, 1);
        return_nil(result);
        return;
    }
    graal_isolatethread_t *thread = java_thread();
    if (thread != NULL) {
        minecraft_touch_up(thread, (int)variant_int(args[0]));
    }
    set_call_ok(error);
    return_nil(result);
}

static void method_reset(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    (void)args;
    if (argument_count != 0) {
        set_argument_error(error, (int)argument_count, 0);
        return_nil(result);
        return;
    }
    graal_isolatethread_t *thread = java_thread();
    if (thread != NULL) {
        minecraft_touch_reset(thread);
    }
    set_call_ok(error);
    return_nil(result);
}

static void method_set_virtual_joystick_mask(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    if (argument_count != 1) {
        set_argument_error(error, (int)argument_count, 1);
        return_nil(result);
        return;
    }
    graal_isolatethread_t *thread = java_thread();
    if (thread != NULL) {
        minecraft_set_virtual_joystick_mask(thread, (int)variant_int(args[0]));
    }
    set_call_ok(error);
    return_nil(result);
}

static void method_get_touch_mask(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    (void)args;
    if (argument_count != 0) {
        set_argument_error(error, (int)argument_count, 0);
        return_int(result, 0);
        return;
    }
    graal_isolatethread_t *thread = java_thread();
    int64_t mask = thread == NULL ? 0 : minecraft_touch_mask(thread);
    set_call_ok(error);
    return_int(result, mask);
}

static void method_get_active_touch_count(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    (void)args;
    if (argument_count != 0) {
        set_argument_error(error, (int)argument_count, 0);
        return_int(result, 0);
        return;
    }
    graal_isolatethread_t *thread = java_thread();
    int64_t count = thread == NULL ? 0 : minecraft_active_touch_count(thread);
    set_call_ok(error);
    return_int(result, count);
}

static void ptrcall_touch_down(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstTypePtr *args, GDExtensionTypePtr result) {
    (void)userdata; (void)instance; (void)result;
    graal_isolatethread_t *thread = java_thread();
    if (thread != NULL) {
        minecraft_touch_down(thread, (int)*(const int64_t *)args[0], (int)*(const int64_t *)args[1],
                (int)*(const int64_t *)args[2], (int)*(const int64_t *)args[3], (int)*(const int64_t *)args[4]);
    }
}

static void ptrcall_touch_move(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstTypePtr *args, GDExtensionTypePtr result) {
    (void)userdata; (void)instance; (void)result;
    graal_isolatethread_t *thread = java_thread();
    if (thread != NULL) {
        minecraft_touch_move(thread, (int)*(const int64_t *)args[0], (int)*(const int64_t *)args[1],
                (int)*(const int64_t *)args[2], (int)*(const int64_t *)args[3], (int)*(const int64_t *)args[4]);
    }
}

static void ptrcall_touch_up(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstTypePtr *args, GDExtensionTypePtr result) {
    (void)userdata; (void)instance; (void)result;
    graal_isolatethread_t *thread = java_thread();
    if (thread != NULL) {
        minecraft_touch_up(thread, (int)*(const int64_t *)args[0]);
    }
}

static void ptrcall_reset(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstTypePtr *args, GDExtensionTypePtr result) {
    (void)userdata; (void)instance; (void)args; (void)result;
    graal_isolatethread_t *thread = java_thread();
    if (thread != NULL) {
        minecraft_touch_reset(thread);
    }
}

static void ptrcall_set_virtual_joystick_mask(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstTypePtr *args, GDExtensionTypePtr result) {
    (void)userdata; (void)instance; (void)result;
    graal_isolatethread_t *thread = java_thread();
    if (thread != NULL) {
        minecraft_set_virtual_joystick_mask(thread, (int)*(const int64_t *)args[0]);
    }
}

static void ptrcall_get_touch_mask(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstTypePtr *args, GDExtensionTypePtr result) {
    (void)userdata; (void)instance; (void)args;
    graal_isolatethread_t *thread = java_thread();
    *(int64_t *)result = thread == NULL ? 0 : minecraft_touch_mask(thread);
}

static void ptrcall_get_active_touch_count(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstTypePtr *args, GDExtensionTypePtr result) {
    (void)userdata; (void)instance; (void)args;
    graal_isolatethread_t *thread = java_thread();
    *(int64_t *)result = thread == NULL ? 0 : minecraft_active_touch_count(thread);
}

static void register_method(const char *name, uint32_t argument_count,
        GDExtensionClassMethodCall call, GDExtensionClassMethodPtrCall ptrcall,
        GDExtensionBool has_return_value) {
    GDExtensionStringNamePtr method_name = make_string_name(name);
    GDExtensionPropertyInfo return_info = {0};
    return_info.type = GDEXTENSION_VARIANT_TYPE_INT;

    GDExtensionPropertyInfo arguments[5] = {0};
    GDExtensionClassMethodArgumentMetadata metadata[5] = {0};
    for (uint32_t i = 0; i < argument_count; i++) {
        arguments[i].type = GDEXTENSION_VARIANT_TYPE_INT;
        metadata[i] = GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT64;
    }

    GDExtensionClassMethodInfo method = {0};
    method.name = method_name;
    method.call_func = call;
    method.ptrcall_func = ptrcall;
    method.method_flags = GDEXTENSION_METHOD_FLAGS_DEFAULT;
    method.has_return_value = has_return_value;
    method.return_value_info = has_return_value ? &return_info : NULL;
    method.return_value_metadata = GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT64;
    method.argument_count = argument_count;
    method.arguments_info = argument_count ? arguments : NULL;
    method.arguments_metadata = argument_count ? metadata : NULL;

    GDExtensionStringNamePtr class_name = make_string_name(CLASS_NAME);
    classdb_register_extension_class_method(godot_library, class_name, &method);
    free_string_name(class_name);
    free_string_name(method_name);
}

static void initialize_minecraft(void *userdata, GDExtensionInitializationLevel level) {
    (void)userdata;
    if (level != GDEXTENSION_INITIALIZATION_SCENE) {
        return;
    }

    if (!java_start()) {
        return;
    }

    GDExtensionStringNamePtr class_name = make_string_name(CLASS_NAME);
    GDExtensionStringNamePtr parent_name = make_string_name(PARENT_CLASS_NAME);
    GDExtensionClassCreationInfo class_info = {0};
    class_info.is_virtual = 0;
    class_info.is_abstract = 0;
    class_info.create_instance_func = minecraft_touch_create;
    class_info.free_instance_func = minecraft_touch_free;
    classdb_register_extension_class(godot_library, class_name, parent_name, &class_info);
    free_string_name(parent_name);
    free_string_name(class_name);

    register_method("touch_down", 5, method_touch_down, ptrcall_touch_down, 0);
    register_method("touch_move", 5, method_touch_move, ptrcall_touch_move, 0);
    register_method("touch_up", 1, method_touch_up, ptrcall_touch_up, 0);
    register_method("reset", 0, method_reset, ptrcall_reset, 0);
    register_method("set_virtual_joystick_mask", 1, method_set_virtual_joystick_mask,
            ptrcall_set_virtual_joystick_mask, 0);
    register_method("get_touch_mask", 0, method_get_touch_mask, ptrcall_get_touch_mask, 1);
    register_method("get_active_touch_count", 0, method_get_active_touch_count,
            ptrcall_get_active_touch_count, 1);
}

static void deinitialize_minecraft(void *userdata, GDExtensionInitializationLevel level) {
    (void)userdata;
    if (level != GDEXTENSION_INITIALIZATION_SCENE || java_isolate == NULL) {
        return;
    }
    graal_isolatethread_t *thread = java_thread();
    if (thread != NULL) {
        minecraft_touch_reset(thread);
        graal_tear_down_isolate(thread);
    }
    java_isolate = NULL;
    java_main_thread = NULL;
}

GDExtensionBool GDEXTENSION_EXPORT godot_gdextension_init(
        GDExtensionInterfaceGetProcAddress get_proc_address,
        GDExtensionClassLibraryPtr library,
        GDExtensionInitialization *initialization) {
    godot_get_proc_address = get_proc_address;
    godot_library = library;

    string_name_new = LOAD_GODOT_INTERFACE(GDExtensionInterfaceStringNameNewWithUtf8Chars,
            "string_name_new_with_utf8_chars");
    classdb_construct_object = LOAD_GODOT_INTERFACE(GDExtensionInterfaceClassdbConstructObject,
            "classdb_construct_object");
    object_set_instance = LOAD_GODOT_INTERFACE(GDExtensionInterfaceObjectSetInstance,
            "object_set_instance");
    classdb_register_extension_class = LOAD_GODOT_INTERFACE(
            GDExtensionInterfaceClassdbRegisterExtensionClass, "classdb_register_extension_class");
    classdb_register_extension_class_method = LOAD_GODOT_INTERFACE(
            GDExtensionInterfaceClassdbRegisterExtensionClassMethod,
            "classdb_register_extension_class_method");
    variant_to_int = LOAD_GODOT_INTERFACE(GDExtensionInterfaceGetVariantToTypeConstructor,
            "get_variant_to_type_constructor");
    variant_from_int = LOAD_GODOT_INTERFACE(GDExtensionInterfaceGetVariantFromTypeConstructor,
            "get_variant_from_type_constructor");
    variant_new_nil = LOAD_GODOT_INTERFACE(GDExtensionInterfaceVariantNewNil, "variant_new_nil");

    if (string_name_new == NULL || classdb_construct_object == NULL || object_set_instance == NULL ||
            classdb_register_extension_class == NULL ||
            classdb_register_extension_class_method == NULL || variant_to_int == NULL ||
            variant_from_int == NULL || variant_new_nil == NULL) {
        return 0;
    }

    initialization->minimum_initialization_level = GDEXTENSION_INITIALIZATION_SCENE;
    initialization->userdata = NULL;
    initialization->initialize = initialize_minecraft;
    initialization->deinitialize = deinitialize_minecraft;
    return 1;
}
