/*
 * Godot C-ABI adapter for the GraalVM-compiled Minecraft input surface.
 * The Java layer does not know about Godot. This adapter owns the GDExtension
 * ABI and forwards plain integer touch data to the Java Native Image library.
 */
#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif
#include <dlfcn.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "gdextension_interface.h"
#include "minecraft_java.h" /* generated by build.sh from native-image output */
#include "minecraft_render_abi.h"
#include "minecraft_render_native_state.h"

#if defined(_WIN32)
#define GDEXTENSION_EXPORT __declspec(dllexport)
#else
#define GDEXTENSION_EXPORT __attribute__((visibility("default")))
#endif

#define CLASS_NAME "MinecraftTouch"
#define PARENT_CLASS_NAME "RefCounted"

/* gdextension_interface.h returns a generic function pointer. The Godot API
 * explicitly permits an intermediate void-pointer cast for typed interfaces. */
#define LOAD_GODOT_INTERFACE(type, name) ((type)(void *)get_proc_address(name))

typedef struct {
    int placeholder;
} MinecraftTouchInstance;

static GDExtensionInterfaceGetProcAddress godot_get_proc_address;
static GDExtensionClassLibraryPtr godot_library;
static GDExtensionInterfaceStringNameNewWithUtf8Chars string_name_new;
static GDExtensionInterfaceClassdbConstructObject classdb_construct_object;
static GDExtensionInterfaceObjectSetInstance object_set_instance;
static GDExtensionInterfaceClassdbRegisterExtensionClass classdb_register_extension_class;
static GDExtensionInterfaceClassdbRegisterExtensionClassMethod classdb_register_extension_class_method;
static GDExtensionInterfaceGetVariantToTypeConstructor variant_to_int;
static GDExtensionInterfaceGetVariantFromTypeConstructor variant_from_int;
static GDExtensionInterfaceVariantNewNil variant_new_nil;
static GDExtensionInterfaceVariantConstruct variant_construct;
static GDExtensionInterfaceVariantCall variant_call;
static GDExtensionInterfaceVariantDestroy variant_destroy;
static GDExtensionInterfaceGetVariantGetInternalPtrFunc variant_get_internal_ptr;
static GDExtensionInterfacePackedByteArrayOperatorIndex packed_byte_array_index;

/* Godot's stable GDExtension Variant ABI reserves 24 bytes, aligned to 64-bit.
 * This is only used for temporary Variant arguments/returns constructed through
 * Godot's own ABI functions; no Godot C++ layout is assumed. */
typedef union MinecraftGodotVariant {
    uint8_t bytes[24];
    uint64_t alignment;
} MinecraftGodotVariant;

static graal_isolate_t *java_isolate;
static graal_isolatethread_t *java_main_thread;
static MinecraftRenderNativeState *render_native_state;

static GDExtensionStringNamePtr make_string_name(const char *text) {
    /* Official Godot 4.7 StringName is one pointer. Every C ABI function takes
     * a pointer to that object; returning the interned data pointer stored
     * inside it would make ClassDB/Variant calls read the wrong memory. */
    void *storage = calloc(1, sizeof(void *));
    if (storage == NULL) {
        return NULL;
    }
    string_name_new(storage, text);
    return storage;
}

/* Godot interns StringNames created through the C ABI. They are kept for the
 * process lifetime so all names used by this small extension are created once
 * per registration/lifetime and intentionally not freed here. */
static void free_string_name(GDExtensionStringNamePtr name) {
    (void)name;
}

static graal_isolatethread_t *java_thread(void) {
    if (java_isolate == NULL) {
        return NULL;
    }
    graal_isolatethread_t *thread = graal_get_current_thread(java_isolate);
    if (thread == NULL && graal_attach_thread(java_isolate, &thread) != 0) {
        return NULL;
    }
    return thread;
}

GDExtensionBool godot_gdextension_init(
        GDExtensionInterfaceGetProcAddress get_proc_address,
        GDExtensionClassLibraryPtr library,
        GDExtensionInitialization *initialization);

/* Point LWJGL at the natives directory beside this extension before the
 * isolate starts, so the extracted client loads the SDL viewport stub. */
static void export_native_dir(void) {
    Dl_info info;
    char path[4096];
    char natives[4096];
    const char *slash;
    size_t length;
    if (getenv("MINECRAFT_GODOT_NATIVE_DIR") != NULL) {
        return;
    }
    if (dladdr((void *)godot_gdextension_init, &info) == 0 || info.dli_fname == NULL) {
        return;
    }
    length = strlen(info.dli_fname);
    if (length == 0 || length >= sizeof(path)) {
        return;
    }
    memcpy(path, info.dli_fname, length + 1);
    slash = strrchr(path, '/');
    if (slash == NULL || slash == path) {
        return;
    }
    snprintf(natives, sizeof(natives), "%.*s/natives", (int)(slash - path), path);
    if (access(natives, R_OK) == 0) {
        setenv("MINECRAFT_GODOT_NATIVE_DIR", natives, 0);
        return;
    }
    path[slash - path] = '\0';
    setenv("MINECRAFT_GODOT_NATIVE_DIR", path, 0);
}

static int java_start(void) {
    graal_create_isolate_params_t params;
    char arg0[] = "minecraft";
    char *isolate_argv[] = {arg0, NULL};
    int status;
    if (java_isolate != NULL) {
        return 1;
    }
    export_native_dir();
    memset(&params, 0, sizeof(params));
    params.version = __graal_create_isolate_params_version;
    /* The extracted client image is large. The default reservation can fail
     * before any Java code runs. */
    params.reserved_address_space_size = (unsigned long)16 * 1024 * 1024 * 1024;
    params.argc = 1;
    params.argv = isolate_argv;
    params.ignore_unrecognized_args = 1;
    status = graal_create_isolate(&params, &java_isolate, &java_main_thread);
    if (status != 0) {
        java_isolate = NULL;
        java_main_thread = NULL;
        return 0;
    }
    minecraft_bootstrap(java_main_thread);
    return 1;
}

static void set_call_ok(GDExtensionCallError *error) {
    if (error != NULL) {
        error->error = GDEXTENSION_CALL_OK;
        error->argument = 0;
        error->expected = 0;
    }
}

static void set_argument_error(GDExtensionCallError *error, int argument, int expected) {
    if (error != NULL) {
        error->error = GDEXTENSION_CALL_ERROR_INVALID_ARGUMENT;
        error->argument = argument;
        error->expected = expected;
    }
}

static int64_t variant_int(GDExtensionConstVariantPtr value) {
    int64_t result = 0;
    GDExtensionTypeFromVariantConstructorFunc converter =
            variant_to_int(GDEXTENSION_VARIANT_TYPE_INT);
    converter(&result, (GDExtensionVariantPtr)value);
    return result;
}

static void return_int(GDExtensionVariantPtr result, int64_t value) {
    GDExtensionVariantFromTypeConstructorFunc constructor =
            variant_from_int(GDEXTENSION_VARIANT_TYPE_INT);
    constructor(result, &value);
}

static void return_nil(GDExtensionVariantPtr result) {
    variant_new_nil(result);
}

/*
 * Copies one bounded native range into a real PackedByteArray Variant. The
 * extension deliberately builds this through the public 4.7 ABI rather than
 * treating PackedByteArray as a C struct: Godot allocates/owns all Variant and
 * packed-array memory, and the caller receives an ordinary GDScript value.
 */
static bool return_packed_bytes(GDExtensionVariantPtr result, const uint8_t *bytes, size_t size) {
    static const uint8_t empty_byte = 0;
    if (bytes == NULL && size == 0) {
        bytes = &empty_byte;
    }
    if (bytes == NULL || size > MINECRAFT_RENDER_BRIDGE_MAX_CHUNK_BYTES ||
            size > INT64_MAX || variant_construct == NULL || variant_call == NULL ||
            variant_destroy == NULL || variant_get_internal_ptr == NULL ||
            packed_byte_array_index == NULL) {
        return false;
    }

    GDExtensionCallError call_error = {0};
    variant_construct(GDEXTENSION_VARIANT_TYPE_PACKED_BYTE_ARRAY, result, NULL, 0, &call_error);
    if (call_error.error != GDEXTENSION_CALL_OK) {
        return false;
    }
    if (size != 0) {
        MinecraftGodotVariant length_argument = {0};
        MinecraftGodotVariant resize_result = {0};
        int64_t length = (int64_t)size;
        GDExtensionVariantFromTypeConstructorFunc int_constructor =
                variant_from_int(GDEXTENSION_VARIANT_TYPE_INT);
        int_constructor(&length_argument, &length);
        static GDExtensionStringNamePtr resize_name;
        if (resize_name == NULL) {
            resize_name = make_string_name("resize");
        }
        if (resize_name == NULL) {
            variant_destroy(result);
            variant_destroy(&length_argument);
            return false;
        }
        const GDExtensionConstVariantPtr arguments[] = { &length_argument };
        variant_call(result, resize_name, arguments, 1, &resize_result, &call_error);
        int64_t resize_status = -1;
        if (call_error.error == GDEXTENSION_CALL_OK) {
            GDExtensionTypeFromVariantConstructorFunc int_reader =
                    variant_to_int(GDEXTENSION_VARIANT_TYPE_INT);
            int_reader(&resize_status, &resize_result);
        }
        variant_destroy(&length_argument);
        variant_destroy(&resize_result);
        if (call_error.error != GDEXTENSION_CALL_OK || resize_status != 0) {
            variant_destroy(result);
            return false;
        }
        GDExtensionVariantGetInternalPtrFunc get_packed_bytes =
                variant_get_internal_ptr(GDEXTENSION_VARIANT_TYPE_PACKED_BYTE_ARRAY);
        GDExtensionTypePtr packed_bytes = get_packed_bytes(result);
        uint8_t *destination = packed_bytes == NULL ? NULL : packed_byte_array_index(packed_bytes, 0);
        if (destination == NULL) {
            variant_destroy(result);
            return false;
        }
        memcpy(destination, bytes, size);
    }
    return true;
}

static GDExtensionObjectPtr minecraft_touch_create(void *class_userdata) {
    (void)class_userdata;
    GDExtensionStringNamePtr class_name = make_string_name(CLASS_NAME);
    GDExtensionObjectPtr object = classdb_construct_object(class_name);
    MinecraftTouchInstance *instance = calloc(1, sizeof(*instance));
    if (object != NULL && instance != NULL) {
        object_set_instance(object, class_name, instance);
    } else {
        free(instance);
    }
    free_string_name(class_name);
    return object;
}

static void minecraft_touch_free(void *class_userdata, GDExtensionClassInstancePtr instance) {
    (void)class_userdata;
    free(instance);
}

static void method_touch_down(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    if (argument_count != 5) {
        set_argument_error(error, (int)argument_count, 5);
        return_nil(result);
        return;
    }
    graal_isolatethread_t *thread = java_thread();
    if (thread != NULL) {
        minecraft_touch_down(thread, (int)variant_int(args[0]), (int)variant_int(args[1]),
                (int)variant_int(args[2]), (int)variant_int(args[3]), (int)variant_int(args[4]));
    }
    set_call_ok(error);
    return_nil(result);
}

static void method_touch_move(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    if (argument_count != 5) {
        set_argument_error(error, (int)argument_count, 5);
        return_nil(result);
        return;
    }
    graal_isolatethread_t *thread = java_thread();
    if (thread != NULL) {
        minecraft_touch_move(thread, (int)variant_int(args[0]), (int)variant_int(args[1]),
                (int)variant_int(args[2]), (int)variant_int(args[3]), (int)variant_int(args[4]));
    }
    set_call_ok(error);
    return_nil(result);
}

static void method_touch_up(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    if (argument_count != 1) {
        set_argument_error(error, (int)argument_count, 1);
        return_nil(result);
        return;
    }
    graal_isolatethread_t *thread = java_thread();
    if (thread != NULL) {
        minecraft_touch_up(thread, (int)variant_int(args[0]));
    }
    set_call_ok(error);
    return_nil(result);
}

static void method_reset(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    (void)args;
    if (argument_count != 0) {
        set_argument_error(error, (int)argument_count, 0);
        return_nil(result);
        return;
    }
    graal_isolatethread_t *thread = java_thread();
    if (thread != NULL) {
        minecraft_touch_reset(thread);
    }
    set_call_ok(error);
    return_nil(result);
}

static void method_add_camera_drag(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    if (argument_count != 2) {
        set_argument_error(error, (int)argument_count, 2);
        return_nil(result);
        return;
    }
    graal_isolatethread_t *thread = java_thread();
    if (thread != NULL) {
        minecraft_add_camera_drag(thread, (int)variant_int(args[0]), (int)variant_int(args[1]));
    }
    set_call_ok(error);
    return_nil(result);
}

static void method_set_virtual_joystick_mask(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    if (argument_count != 1) {
        set_argument_error(error, (int)argument_count, 1);
        return_nil(result);
        return;
    }
    graal_isolatethread_t *thread = java_thread();
    if (thread != NULL) {
        minecraft_set_virtual_joystick_mask(thread, (int)variant_int(args[0]));
    }
    set_call_ok(error);
    return_nil(result);
}

static void method_submit_render_protocol_smoke_frame(void *userdata,
        GDExtensionClassInstancePtr instance, const GDExtensionConstVariantPtr *args,
        GDExtensionInt argument_count, GDExtensionVariantPtr result,
        GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    (void)args;
    if (argument_count != 0) {
        set_argument_error(error, (int)argument_count, 0);
        return_int(result, MINECRAFT_RENDER_INVALID_ARGUMENT);
        return;
    }
    graal_isolatethread_t *thread = java_thread();
    int64_t packet_count = thread == NULL ? MINECRAFT_RENDER_INVALID_ARGUMENT :
            minecraft_render_submit_protocol_smoke_frame(thread);
    set_call_ok(error);
    return_int(result, packet_count);
}

static void method_execute_render_mailbox(void *userdata,
        GDExtensionClassInstancePtr instance, const GDExtensionConstVariantPtr *args,
        GDExtensionInt argument_count, GDExtensionVariantPtr result,
        GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    (void)args;
    if (argument_count != 0) {
        set_argument_error(error, (int)argument_count, 0);
        return_int(result, MINECRAFT_RENDER_INVALID_ARGUMENT);
        return;
    }
    set_call_ok(error);
    return_int(result, minecraft_render_native_execute_latest(render_native_state));
}

static void method_get_render_buffer_count(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    (void)args;
    if (argument_count != 0) {
        set_argument_error(error, (int)argument_count, 0);
        return_int(result, 0);
        return;
    }
    set_call_ok(error);
    return_int(result, (int64_t)minecraft_render_native_buffer_count(render_native_state));
}

static void method_get_render_buffer_attribute(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    if (argument_count != 2) {
        set_argument_error(error, (int)argument_count, 2);
        return_int(result, 0);
        return;
    }
    int64_t index = variant_int(args[0]);
    int64_t attribute = variant_int(args[1]);
    if (index < 0 || attribute < 0) {
        set_argument_error(error, index < 0 ? 0 : 1, 0);
        return_int(result, 0);
        return;
    }
    uint64_t value = minecraft_render_native_buffer_attribute_at(
            render_native_state, (size_t)index, (uint32_t)attribute
    );
    set_call_ok(error);
    return_int(result, (int64_t)value);
}

static void method_get_render_texture_count(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    (void)args;
    if (argument_count != 0) {
        set_argument_error(error, (int)argument_count, 0);
        return_int(result, 0);
        return;
    }
    set_call_ok(error);
    return_int(result, (int64_t)minecraft_render_native_texture_count(render_native_state));
}

static void method_get_render_texture_attribute(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    if (argument_count != 2) {
        set_argument_error(error, (int)argument_count, 2);
        return_int(result, 0);
        return;
    }
    int64_t index = variant_int(args[0]);
    int64_t attribute = variant_int(args[1]);
    if (index < 0 || attribute < 0) {
        set_argument_error(error, index < 0 ? 0 : 1, 0);
        return_int(result, 0);
        return;
    }
    uint32_t value = minecraft_render_native_texture_attribute_at(
            render_native_state, (size_t)index, (uint32_t)attribute
    );
    set_call_ok(error);
    return_int(result, value);
}

static void method_get_render_buffer_bytes(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    if (argument_count != 3) {
        set_argument_error(error, (int)argument_count, 3);
        return_nil(result);
        return;
    }
    int64_t buffer_id = variant_int(args[0]);
    int64_t offset = variant_int(args[1]);
    int64_t byte_count = variant_int(args[2]);
    if (buffer_id <= 0 || offset < 0 || byte_count <= 0 ||
            (uint64_t)byte_count > MINECRAFT_RENDER_BRIDGE_MAX_CHUNK_BYTES) {
        set_argument_error(error, buffer_id <= 0 ? 0 : (offset < 0 ? 1 : 2), 0);
        return_nil(result);
        return;
    }
    uint8_t *copy = malloc((size_t)byte_count);
    size_t copied = copy == NULL ? 0 : minecraft_render_native_copy_buffer_bytes(
            render_native_state, (uint32_t)buffer_id, (uint64_t)offset, copy, (size_t)byte_count
    );
    bool ok = copied == (size_t)byte_count && return_packed_bytes(result, copy, copied);
    free(copy);
    if (!ok) {
        return_nil(result);
    }
    set_call_ok(error);
}

static void method_get_render_texture_mip_layer_size(void *userdata,
        GDExtensionClassInstancePtr instance, const GDExtensionConstVariantPtr *args,
        GDExtensionInt argument_count, GDExtensionVariantPtr result,
        GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    if (argument_count != 3) {
        set_argument_error(error, (int)argument_count, 3);
        return_int(result, 0);
        return;
    }
    int64_t texture_id = variant_int(args[0]);
    int64_t mip_level = variant_int(args[1]);
    int64_t layer = variant_int(args[2]);
    if (texture_id <= 0 || mip_level < 0 || layer < 0) {
        set_argument_error(error, texture_id <= 0 ? 0 : (mip_level < 0 ? 1 : 2), 0);
        return_int(result, 0);
        return;
    }
    uint64_t size = minecraft_render_native_texture_mip_layer_size(
            render_native_state, (uint32_t)texture_id, (uint32_t)mip_level, (uint32_t)layer
    );
    set_call_ok(error);
    return_int(result, (int64_t)size);
}

static void method_get_render_texture_mip_layer_bytes(void *userdata,
        GDExtensionClassInstancePtr instance, const GDExtensionConstVariantPtr *args,
        GDExtensionInt argument_count, GDExtensionVariantPtr result,
        GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    if (argument_count != 5) {
        set_argument_error(error, (int)argument_count, 5);
        return_nil(result);
        return;
    }
    int64_t texture_id = variant_int(args[0]);
    int64_t mip_level = variant_int(args[1]);
    int64_t layer = variant_int(args[2]);
    int64_t offset = variant_int(args[3]);
    int64_t byte_count = variant_int(args[4]);
    if (texture_id <= 0 || mip_level < 0 || layer < 0 || offset < 0 || byte_count <= 0 ||
            (uint64_t)byte_count > MINECRAFT_RENDER_BRIDGE_MAX_CHUNK_BYTES) {
        set_argument_error(error, texture_id <= 0 ? 0 :
                (mip_level < 0 ? 1 : (layer < 0 ? 2 : (offset < 0 ? 3 : 4))), 0);
        return_nil(result);
        return;
    }
    uint8_t *copy = malloc((size_t)byte_count);
    size_t copied = copy == NULL ? 0 : minecraft_render_native_copy_texture_mip_layer_bytes(
            render_native_state, (uint32_t)texture_id, (uint32_t)mip_level, (uint32_t)layer,
            (uint64_t)offset, copy, (size_t)byte_count
    );
    bool ok = copied == (size_t)byte_count && return_packed_bytes(result, copy, copied);
    free(copy);
    if (!ok) {
        return_nil(result);
    }
    set_call_ok(error);
}

static void method_get_render_pass_attribute(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    if (argument_count != 1) {
        set_argument_error(error, (int)argument_count, 1);
        return_int(result, 0);
        return;
    }
    int64_t attribute = variant_int(args[0]);
    if (attribute < 0) {
        set_argument_error(error, 0, 0);
        return_int(result, 0);
        return;
    }
    set_call_ok(error);
    return_int(result, minecraft_render_native_pass_attribute(
            render_native_state, (uint32_t)attribute
    ));
}

static void method_get_touch_mask(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    (void)args;
    if (argument_count != 0) {
        set_argument_error(error, (int)argument_count, 0);
        return_int(result, 0);
        return;
    }
    graal_isolatethread_t *thread = java_thread();
    int64_t mask = thread == NULL ? 0 : minecraft_touch_mask(thread);
    set_call_ok(error);
    return_int(result, mask);
}

static void method_get_active_touch_count(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    (void)args;
    if (argument_count != 0) {
        set_argument_error(error, (int)argument_count, 0);
        return_int(result, 0);
        return;
    }
    graal_isolatethread_t *thread = java_thread();
    int64_t count = thread == NULL ? 0 : minecraft_active_touch_count(thread);
    set_call_ok(error);
    return_int(result, count);
}

static void ptrcall_touch_down(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstTypePtr *args, GDExtensionTypePtr result) {
    (void)userdata; (void)instance; (void)result;
    graal_isolatethread_t *thread = java_thread();
    if (thread != NULL) {
        minecraft_touch_down(thread, (int)*(const int64_t *)args[0], (int)*(const int64_t *)args[1],
                (int)*(const int64_t *)args[2], (int)*(const int64_t *)args[3], (int)*(const int64_t *)args[4]);
    }
}

static void ptrcall_touch_move(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstTypePtr *args, GDExtensionTypePtr result) {
    (void)userdata; (void)instance; (void)result;
    graal_isolatethread_t *thread = java_thread();
    if (thread != NULL) {
        minecraft_touch_move(thread, (int)*(const int64_t *)args[0], (int)*(const int64_t *)args[1],
                (int)*(const int64_t *)args[2], (int)*(const int64_t *)args[3], (int)*(const int64_t *)args[4]);
    }
}

static void ptrcall_touch_up(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstTypePtr *args, GDExtensionTypePtr result) {
    (void)userdata; (void)instance; (void)result;
    graal_isolatethread_t *thread = java_thread();
    if (thread != NULL) {
        minecraft_touch_up(thread, (int)*(const int64_t *)args[0]);
    }
}

static void ptrcall_reset(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstTypePtr *args, GDExtensionTypePtr result) {
    (void)userdata; (void)instance; (void)args; (void)result;
    graal_isolatethread_t *thread = java_thread();
    if (thread != NULL) {
        minecraft_touch_reset(thread);
    }
}

static void ptrcall_add_camera_drag(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstTypePtr *args, GDExtensionTypePtr result) {
    (void)userdata; (void)instance; (void)result;
    graal_isolatethread_t *thread = java_thread();
    if (thread != NULL) {
        minecraft_add_camera_drag(thread, (int)*(const int64_t *)args[0],
                (int)*(const int64_t *)args[1]);
    }
}

static void ptrcall_set_virtual_joystick_mask(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstTypePtr *args, GDExtensionTypePtr result) {
    (void)userdata; (void)instance; (void)result;
    graal_isolatethread_t *thread = java_thread();
    if (thread != NULL) {
        minecraft_set_virtual_joystick_mask(thread, (int)*(const int64_t *)args[0]);
    }
}

static void ptrcall_submit_render_protocol_smoke_frame(void *userdata,
        GDExtensionClassInstancePtr instance, const GDExtensionConstTypePtr *args,
        GDExtensionTypePtr result) {
    (void)userdata;
    (void)instance;
    (void)args;
    graal_isolatethread_t *thread = java_thread();
    *(int64_t *)result = thread == NULL ? MINECRAFT_RENDER_INVALID_ARGUMENT :
            minecraft_render_submit_protocol_smoke_frame(thread);
}

static void ptrcall_execute_render_mailbox(void *userdata,
        GDExtensionClassInstancePtr instance, const GDExtensionConstTypePtr *args,
        GDExtensionTypePtr result) {
    (void)userdata;
    (void)instance;
    (void)args;
    *(int64_t *)result = minecraft_render_native_execute_latest(render_native_state);
}

static void ptrcall_get_render_buffer_count(void *userdata,
        GDExtensionClassInstancePtr instance, const GDExtensionConstTypePtr *args,
        GDExtensionTypePtr result) {
    (void)userdata;
    (void)instance;
    (void)args;
    *(int64_t *)result = (int64_t)minecraft_render_native_buffer_count(render_native_state);
}

static void ptrcall_get_render_buffer_attribute(void *userdata,
        GDExtensionClassInstancePtr instance, const GDExtensionConstTypePtr *args,
        GDExtensionTypePtr result) {
    (void)userdata;
    (void)instance;
    int64_t index = *(const int64_t *)args[0];
    int64_t attribute = *(const int64_t *)args[1];
    if (index < 0 || attribute < 0) {
        *(int64_t *)result = 0;
        return;
    }
    *(int64_t *)result = (int64_t)minecraft_render_native_buffer_attribute_at(
            render_native_state, (size_t)index, (uint32_t)attribute
    );
}

static void ptrcall_get_render_texture_count(void *userdata,
        GDExtensionClassInstancePtr instance, const GDExtensionConstTypePtr *args,
        GDExtensionTypePtr result) {
    (void)userdata;
    (void)instance;
    (void)args;
    *(int64_t *)result = (int64_t)minecraft_render_native_texture_count(render_native_state);
}

static void ptrcall_get_render_texture_attribute(void *userdata,
        GDExtensionClassInstancePtr instance, const GDExtensionConstTypePtr *args,
        GDExtensionTypePtr result) {
    (void)userdata;
    (void)instance;
    int64_t index = *(const int64_t *)args[0];
    int64_t attribute = *(const int64_t *)args[1];
    *(int64_t *)result = index < 0 || attribute < 0 ? 0 :
            (int64_t)minecraft_render_native_texture_attribute_at(
                    render_native_state, (size_t)index, (uint32_t)attribute
            );
}

static void ptrcall_get_render_pass_attribute(void *userdata,
        GDExtensionClassInstancePtr instance, const GDExtensionConstTypePtr *args,
        GDExtensionTypePtr result) {
    (void)userdata;
    (void)instance;
    int64_t attribute = *(const int64_t *)args[0];
    *(int64_t *)result = attribute < 0 ? 0 :
            (int64_t)minecraft_render_native_pass_attribute(render_native_state, (uint32_t)attribute);
}

static void ptrcall_get_touch_mask(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstTypePtr *args, GDExtensionTypePtr result) {
    (void)userdata; (void)instance; (void)args;
    graal_isolatethread_t *thread = java_thread();
    *(int64_t *)result = thread == NULL ? 0 : minecraft_touch_mask(thread);
}

static void ptrcall_get_active_touch_count(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstTypePtr *args, GDExtensionTypePtr result) {
    (void)userdata; (void)instance; (void)args;
    graal_isolatethread_t *thread = java_thread();
    *(int64_t *)result = thread == NULL ? 0 : minecraft_active_touch_count(thread);
}


static void method_get_render_frame_pass_count(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    (void)args;
    if (argument_count != 0) {
        set_argument_error(error, (int)argument_count, 0);
        return_int(result, 0);
        return;
    }
    set_call_ok(error);
    return_int(result, (int64_t)minecraft_render_native_frame_pass_count(render_native_state));
}

static void method_get_render_frame_pass_attribute(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    if (argument_count != 2) {
        set_argument_error(error, (int)argument_count, 2);
        return_int(result, 0);
        return;
    }
    int64_t index = variant_int(args[0]);
    int64_t attribute = variant_int(args[1]);
    if (index < 0 || attribute < 0) {
        set_argument_error(error, index < 0 ? 0 : 1, 0);
        return_int(result, 0);
        return;
    }
    set_call_ok(error);
    return_int(result, minecraft_render_native_frame_pass_attribute(
            render_native_state, (size_t)index, (uint32_t)attribute
    ));
}

static void method_get_render_draw_count(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    (void)args;
    if (argument_count != 0) {
        set_argument_error(error, (int)argument_count, 0);
        return_int(result, 0);
        return;
    }
    set_call_ok(error);
    return_int(result, (int64_t)minecraft_render_native_draw_count(render_native_state));
}

static void method_get_render_draw_attribute(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    if (argument_count != 2) {
        set_argument_error(error, (int)argument_count, 2);
        return_int(result, 0);
        return;
    }
    int64_t index = variant_int(args[0]);
    int64_t attribute = variant_int(args[1]);
    if (index < 0 || attribute < 0) {
        set_argument_error(error, index < 0 ? 0 : 1, 0);
        return_int(result, 0);
        return;
    }
    set_call_ok(error);
    return_int(result, minecraft_render_native_draw_attribute(
            render_native_state, (size_t)index, (uint32_t)attribute
    ));
}

static void method_get_render_pipeline_attribute(void *userdata, GDExtensionClassInstancePtr instance,
        const GDExtensionConstVariantPtr *args, GDExtensionInt argument_count,
        GDExtensionVariantPtr result, GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    if (argument_count != 2) {
        set_argument_error(error, (int)argument_count, 2);
        return_int(result, 0);
        return;
    }
    int64_t pipeline_id = variant_int(args[0]);
    int64_t attribute = variant_int(args[1]);
    if (pipeline_id <= 0 || attribute < 0) {
        set_argument_error(error, pipeline_id <= 0 ? 0 : 1, 0);
        return_int(result, 0);
        return;
    }
    set_call_ok(error);
    return_int(result, minecraft_render_native_pipeline_attribute(
            render_native_state, (uint32_t)pipeline_id, (uint32_t)attribute
    ));
}

static void method_get_render_pipeline_vertex_attribute(void *userdata,
        GDExtensionClassInstancePtr instance, const GDExtensionConstVariantPtr *args,
        GDExtensionInt argument_count, GDExtensionVariantPtr result,
        GDExtensionCallError *error) {
    (void)userdata;
    (void)instance;
    if (argument_count != 3) {
        set_argument_error(error, (int)argument_count, 3);
        return_int(result, 0);
        return;
    }
    int64_t pipeline_id = variant_int(args[0]);
    int64_t attribute_index = variant_int(args[1]);
    int64_t field = variant_int(args[2]);
    if (pipeline_id <= 0 || attribute_index < 0 || field < 0) {
        set_argument_error(error, pipeline_id <= 0 ? 0 : (attribute_index < 0 ? 1 : 2), 0);
        return_int(result, 0);
        return;
    }
    set_call_ok(error);
    return_int(result, minecraft_render_native_pipeline_vertex_attribute(
            render_native_state, (uint32_t)pipeline_id, (uint32_t)attribute_index, (uint32_t)field
    ));
}

static void ptrcall_get_render_frame_pass_count(void *userdata,
        GDExtensionClassInstancePtr instance, const GDExtensionConstTypePtr *args,
        GDExtensionTypePtr result) {
    (void)userdata;
    (void)instance;
    (void)args;
    *(int64_t *)result = (int64_t)minecraft_render_native_frame_pass_count(render_native_state);
}

static void ptrcall_get_render_frame_pass_attribute(void *userdata,
        GDExtensionClassInstancePtr instance, const GDExtensionConstTypePtr *args,
        GDExtensionTypePtr result) {
    (void)userdata;
    (void)instance;
    int64_t index = *(const int64_t *)args[0];
    int64_t attribute = *(const int64_t *)args[1];
    *(int64_t *)result = index < 0 || attribute < 0 ? 0 :
            (int64_t)minecraft_render_native_frame_pass_attribute(
                    render_native_state, (size_t)index, (uint32_t)attribute
            );
}

static void ptrcall_get_render_draw_count(void *userdata,
        GDExtensionClassInstancePtr instance, const GDExtensionConstTypePtr *args,
        GDExtensionTypePtr result) {
    (void)userdata;
    (void)instance;
    (void)args;
    *(int64_t *)result = (int64_t)minecraft_render_native_draw_count(render_native_state);
}

static void ptrcall_get_render_draw_attribute(void *userdata,
        GDExtensionClassInstancePtr instance, const GDExtensionConstTypePtr *args,
        GDExtensionTypePtr result) {
    (void)userdata;
    (void)instance;
    int64_t index = *(const int64_t *)args[0];
    int64_t attribute = *(const int64_t *)args[1];
    *(int64_t *)result = index < 0 || attribute < 0 ? 0 :
            minecraft_render_native_draw_attribute(render_native_state, (size_t)index, (uint32_t)attribute);
}

static void ptrcall_get_render_pipeline_attribute(void *userdata,
        GDExtensionClassInstancePtr instance, const GDExtensionConstTypePtr *args,
        GDExtensionTypePtr result) {
    (void)userdata;
    (void)instance;
    int64_t pipeline_id = *(const int64_t *)args[0];
    int64_t attribute = *(const int64_t *)args[1];
    *(int64_t *)result = pipeline_id <= 0 || attribute < 0 ? 0 :
            minecraft_render_native_pipeline_attribute(
                    render_native_state, (uint32_t)pipeline_id, (uint32_t)attribute
            );
}

static void ptrcall_get_render_pipeline_vertex_attribute(void *userdata,
        GDExtensionClassInstancePtr instance, const GDExtensionConstTypePtr *args,
        GDExtensionTypePtr result) {
    (void)userdata;
    (void)instance;
    int64_t pipeline_id = *(const int64_t *)args[0];
    int64_t attribute_index = *(const int64_t *)args[1];
    int64_t field = *(const int64_t *)args[2];
    *(int64_t *)result = pipeline_id <= 0 || attribute_index < 0 || field < 0 ? 0 :
            minecraft_render_native_pipeline_vertex_attribute(
                    render_native_state, (uint32_t)pipeline_id,
                    (uint32_t)attribute_index, (uint32_t)field
            );
}

static void register_method(const char *name, uint32_t argument_count,
        GDExtensionClassMethodCall call, GDExtensionClassMethodPtrCall ptrcall,
        GDExtensionBool has_return_value) {
    GDExtensionStringNamePtr method_name = make_string_name(name);
    GDExtensionPropertyInfo return_info = {0};
    return_info.type = GDEXTENSION_VARIANT_TYPE_INT;

    GDExtensionPropertyInfo arguments[5] = {0};
    GDExtensionClassMethodArgumentMetadata metadata[5] = {0};
    for (uint32_t i = 0; i < argument_count; i++) {
        arguments[i].type = GDEXTENSION_VARIANT_TYPE_INT;
        metadata[i] = GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT64;
    }

    GDExtensionClassMethodInfo method = {0};
    method.name = method_name;
    method.call_func = call;
    method.ptrcall_func = ptrcall;
    method.method_flags = GDEXTENSION_METHOD_FLAGS_DEFAULT;
    method.has_return_value = has_return_value;
    method.return_value_info = has_return_value ? &return_info : NULL;
    method.return_value_metadata = GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT64;
    method.argument_count = argument_count;
    method.arguments_info = argument_count ? arguments : NULL;
    method.arguments_metadata = argument_count ? metadata : NULL;

    GDExtensionStringNamePtr class_name = make_string_name(CLASS_NAME);
    classdb_register_extension_class_method(godot_library, class_name, &method);
    free_string_name(class_name);
    free_string_name(method_name);
}

/* PackedByteArray returns intentionally use the generic Variant callback only.
 * The data bridge is always invoked through Object.call() from GDScript, which
 * keeps Godot responsible for constructing the opaque packed-array return. */
static void register_packed_byte_array_method(const char *name, uint32_t argument_count,
        GDExtensionClassMethodCall call) {
    GDExtensionStringNamePtr method_name = make_string_name(name);
    GDExtensionPropertyInfo return_info = {0};
    return_info.type = GDEXTENSION_VARIANT_TYPE_PACKED_BYTE_ARRAY;

    GDExtensionPropertyInfo arguments[5] = {0};
    GDExtensionClassMethodArgumentMetadata metadata[5] = {0};
    for (uint32_t i = 0; i < argument_count; i++) {
        arguments[i].type = GDEXTENSION_VARIANT_TYPE_INT;
        metadata[i] = GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT64;
    }

    GDExtensionClassMethodInfo method = {0};
    method.name = method_name;
    method.call_func = call;
    method.ptrcall_func = NULL;
    method.method_flags = GDEXTENSION_METHOD_FLAGS_DEFAULT;
    method.has_return_value = 1;
    method.return_value_info = &return_info;
    method.argument_count = argument_count;
    method.arguments_info = argument_count ? arguments : NULL;
    method.arguments_metadata = argument_count ? metadata : NULL;

    GDExtensionStringNamePtr class_name = make_string_name(CLASS_NAME);
    classdb_register_extension_class_method(godot_library, class_name, &method);
    free_string_name(class_name);
    free_string_name(method_name);
}

static void initialize_minecraft(void *userdata, GDExtensionInitializationLevel level) {
    (void)userdata;
    if (level != GDEXTENSION_INITIALIZATION_SCENE) {
        return;
    }

    if (!java_start()) {
        return;
    }
    render_native_state = minecraft_render_native_state_create();
    if (render_native_state == NULL) {
        return;
    }

    GDExtensionStringNamePtr class_name = make_string_name(CLASS_NAME);
    GDExtensionStringNamePtr parent_name = make_string_name(PARENT_CLASS_NAME);
    GDExtensionClassCreationInfo class_info = {0};
    class_info.is_virtual = 0;
    class_info.is_abstract = 0;
    class_info.create_instance_func = minecraft_touch_create;
    class_info.free_instance_func = minecraft_touch_free;
    classdb_register_extension_class(godot_library, class_name, parent_name, &class_info);
    free_string_name(parent_name);
    free_string_name(class_name);

    register_method("touch_down", 5, method_touch_down, ptrcall_touch_down, 0);
    register_method("touch_move", 5, method_touch_move, ptrcall_touch_move, 0);
    register_method("touch_up", 1, method_touch_up, ptrcall_touch_up, 0);
    register_method("reset", 0, method_reset, ptrcall_reset, 0);
    register_method("add_camera_drag", 2, method_add_camera_drag, ptrcall_add_camera_drag, 0);
    register_method("set_virtual_joystick_mask", 1, method_set_virtual_joystick_mask,
            ptrcall_set_virtual_joystick_mask, 0);
    register_method("submit_render_protocol_smoke_frame", 0,
            method_submit_render_protocol_smoke_frame,
            ptrcall_submit_render_protocol_smoke_frame, 1);
    register_method("execute_render_mailbox", 0, method_execute_render_mailbox,
            ptrcall_execute_render_mailbox, 1);
    register_method("get_render_buffer_count", 0, method_get_render_buffer_count,
            ptrcall_get_render_buffer_count, 1);
    register_method("get_render_buffer_attribute", 2, method_get_render_buffer_attribute,
            ptrcall_get_render_buffer_attribute, 1);
    register_method("get_render_texture_count", 0, method_get_render_texture_count,
            ptrcall_get_render_texture_count, 1);
    register_method("get_render_texture_attribute", 2, method_get_render_texture_attribute,
            ptrcall_get_render_texture_attribute, 1);
    register_method("get_render_pass_attribute", 1, method_get_render_pass_attribute,
            ptrcall_get_render_pass_attribute, 1);
    register_method("get_render_frame_pass_count", 0, method_get_render_frame_pass_count,
            ptrcall_get_render_frame_pass_count, 1);
    register_method("get_render_frame_pass_attribute", 2, method_get_render_frame_pass_attribute,
            ptrcall_get_render_frame_pass_attribute, 1);
    register_method("get_render_draw_count", 0, method_get_render_draw_count,
            ptrcall_get_render_draw_count, 1);
    register_method("get_render_draw_attribute", 2, method_get_render_draw_attribute,
            ptrcall_get_render_draw_attribute, 1);
    register_method("get_render_pipeline_attribute", 2, method_get_render_pipeline_attribute,
            ptrcall_get_render_pipeline_attribute, 1);
    register_method("get_render_pipeline_vertex_attribute", 3,
            method_get_render_pipeline_vertex_attribute,
            ptrcall_get_render_pipeline_vertex_attribute, 1);
    register_method("get_render_texture_mip_layer_size", 3,
            method_get_render_texture_mip_layer_size, NULL, 1);
    register_packed_byte_array_method("get_render_buffer_bytes", 3,
            method_get_render_buffer_bytes);
    register_packed_byte_array_method("get_render_texture_mip_layer_bytes", 5,
            method_get_render_texture_mip_layer_bytes);
    register_method("get_touch_mask", 0, method_get_touch_mask, ptrcall_get_touch_mask, 1);
    register_method("get_active_touch_count", 0, method_get_active_touch_count,
            ptrcall_get_active_touch_count, 1);
}

static void deinitialize_minecraft(void *userdata, GDExtensionInitializationLevel level) {
    (void)userdata;
    if (level != GDEXTENSION_INITIALIZATION_SCENE) {
        return;
    }
    if (java_isolate != NULL) {
        graal_isolatethread_t *thread = java_thread();
        if (thread != NULL) {
            minecraft_client_stop(thread);
            minecraft_touch_reset(thread);
            graal_tear_down_isolate(thread);
        }
        java_isolate = NULL;
        java_main_thread = NULL;
    }
    minecraft_render_native_state_destroy(render_native_state);
    render_native_state = NULL;
    minecraft_render_clear_latest_frame();
}

GDExtensionBool GDEXTENSION_EXPORT godot_gdextension_init(
        GDExtensionInterfaceGetProcAddress get_proc_address,
        GDExtensionClassLibraryPtr library,
        GDExtensionInitialization *initialization) {
    godot_get_proc_address = get_proc_address;
    godot_library = library;

    string_name_new = LOAD_GODOT_INTERFACE(GDExtensionInterfaceStringNameNewWithUtf8Chars,
            "string_name_new_with_utf8_chars");
    classdb_construct_object = LOAD_GODOT_INTERFACE(GDExtensionInterfaceClassdbConstructObject,
            "classdb_construct_object");
    object_set_instance = LOAD_GODOT_INTERFACE(GDExtensionInterfaceObjectSetInstance,
            "object_set_instance");
    classdb_register_extension_class = LOAD_GODOT_INTERFACE(
            GDExtensionInterfaceClassdbRegisterExtensionClass, "classdb_register_extension_class");
    classdb_register_extension_class_method = LOAD_GODOT_INTERFACE(
            GDExtensionInterfaceClassdbRegisterExtensionClassMethod,
            "classdb_register_extension_class_method");
    variant_to_int = LOAD_GODOT_INTERFACE(GDExtensionInterfaceGetVariantToTypeConstructor,
            "get_variant_to_type_constructor");
    variant_from_int = LOAD_GODOT_INTERFACE(GDExtensionInterfaceGetVariantFromTypeConstructor,
            "get_variant_from_type_constructor");
    variant_new_nil = LOAD_GODOT_INTERFACE(GDExtensionInterfaceVariantNewNil, "variant_new_nil");
    variant_construct = LOAD_GODOT_INTERFACE(GDExtensionInterfaceVariantConstruct, "variant_construct");
    variant_call = LOAD_GODOT_INTERFACE(GDExtensionInterfaceVariantCall, "variant_call");
    variant_destroy = LOAD_GODOT_INTERFACE(GDExtensionInterfaceVariantDestroy, "variant_destroy");
    variant_get_internal_ptr = LOAD_GODOT_INTERFACE(GDExtensionInterfaceGetVariantGetInternalPtrFunc,
            "variant_get_ptr_internal_getter");
    packed_byte_array_index = LOAD_GODOT_INTERFACE(GDExtensionInterfacePackedByteArrayOperatorIndex,
            "packed_byte_array_operator_index");

    if (string_name_new == NULL || classdb_construct_object == NULL || object_set_instance == NULL ||
            classdb_register_extension_class == NULL ||
            classdb_register_extension_class_method == NULL || variant_to_int == NULL ||
            variant_from_int == NULL || variant_new_nil == NULL || variant_construct == NULL ||
            variant_call == NULL || variant_destroy == NULL || variant_get_internal_ptr == NULL ||
            packed_byte_array_index == NULL) {
        return 0;
    }

    initialization->minimum_initialization_level = GDEXTENSION_INITIALIZATION_SCENE;
    initialization->userdata = NULL;
    initialization->initialize = initialize_minecraft;
    initialization->deinitialize = deinitialize_minecraft;
    return 1;
}
