#pragma once
// AUTO-GENERATED - Full entity list
// 82 entities
#include <string>
#include <vector>
namespace Eaglercraft26 {
struct AllEntities {
    static inline std::vector<std::string> get_all_entities() {
        return {
            "allay",
            "armadillo",
            "axolotl",
            "bat",
            "bee",
            "blaze",
            "bogged",
            "breeze",
            "camel",
            "cat",
            "cave_spider",
            "chicken",
            "cod",
            "cow",
            "creaking",
            "creeper",
            "dolphin",
            "donkey",
            "drowned",
            "elder_guardian",
            "ender_dragon",
            "enderman",
            "endermite",
            "evoker",
            "fox",
            "frog",
            "ghast",
            "glow_squid",
            "goat",
            "guardian",
            "hoglin",
            "horse",
            "husk",
            "illusioner",
            "iron_golem",
            "llama",
            "magma_cube",
            "mooshroom",
            "mule",
            "ocelot",
            "panda",
            "parrot",
            "phantom",
            "pig",
            "piglin",
            "piglin_brute",
            "pillager",
            "polar_bear",
            "pufferfish",
            "rabbit",
            "ravager",
            "salmon",
            "sheep",
            "shulker",
            "silverfish",
            "skeleton",
            "skeleton_horse",
            "slime",
            "sniffer",
            "snow_golem",
            "spider",
            "squid",
            "stray",
            "strider",
            "tadpole",
            "trader_llama",
            "tropical_fish",
            "turtle",
            "vex",
            "villager",
            "vindicator",
            "wandering_trader",
            "warden",
            "witch",
            "wither",
            "wither_skeleton",
            "wolf",
            "zoglin",
            "zombie",
            "zombie_horse",
            "zombie_villager",
            "zombified_piglin",
        };
    }
    static constexpr int COUNT = 82;
};
}
