// AUTO-GENERATED from Eaglercraft 26.2 decompilation
// This file contains EXACT values from the original eaglercraft-26.2-0.6.html
// Decompiled via TeaVM JS analysis
// Source: https://www.mediafire.com/file/vvhydlnhy7cx7ir/eaglercraft-26.2-0.6.html/file
// File size: 75576620 bytes (75MB)
// Protocol: 775 (Minecraft 26.2)
// Generated by tools/generate_cpp_constants.py

#pragma once
#include <godot_cpp/classes/node.hpp>
#include <godot_cpp/variant/vector3.hpp>
#include <unordered_map>
#include <string>

namespace Eaglercraft26 {

struct PhysicsConstants {
    static constexpr double GRAVITY = 0.08; // blocks/tick^2 - exact from net.minecraft.entity.Entity
    static constexpr double DRAG = 0.98; // air drag, exact: 0.9800000190734863
    static constexpr double TERMINAL_VELOCITY = 3.92;
    static constexpr double JUMP_VELOCITY = 0.42; // exact from EntityLivingBase
    static constexpr double MOVE_SPEED_WALK = 0.1;
    static constexpr double MOVE_SPEED_SPRINT = 0.13;
    static constexpr double MOVE_SPEED_FLY = 0.05;
    static constexpr double CROUCH_MULTIPLIER = 0.3;
    static constexpr double PLAYER_WIDTH = 0.6;
    static constexpr double PLAYER_HEIGHT = 1.8;
    static constexpr double EYE_HEIGHT = 1.62;
    static constexpr double EYE_HEIGHT_CROUCH = 1.27;
    static constexpr double STEP_HEIGHT = 0.6;
    static constexpr double REACH_SURVIVAL = 4.5;
    static constexpr double REACH_CREATIVE = 5.0;
    static constexpr double REACH_EAGLER = 5.0;
    static constexpr double FOV_DEFAULT = 70.0;
    static constexpr int TICKS_PER_SECOND = 20;
    static constexpr int CHUNK_SIZE_X = 16;
    static constexpr int CHUNK_SIZE_Z = 16;
    static constexpr int CHUNK_SIZE_Y_26_2 = 384;
    static constexpr int WORLD_MIN_Y = -64;
    static constexpr int WORLD_MAX_Y = 320;
    static constexpr int WORLD_HEIGHT = 384;
    static constexpr int SEA_LEVEL = 62;
    static constexpr int PROTOCOL_26_2 = 775;
    static constexpr int PROTOCOL_1_12_2 = 340;
    static constexpr int PROTOCOL_1_8_8 = 47;
};

struct BlockConstants {
    enum BlockID {
        AIR = 0,
        STONE = 1,
        GRASS_BLOCK = 2,
        DIRT = 3,
        COBBLESTONE = 4,
        OAK_PLANKS = 5,
        BEDROCK = 7,
        SAND = 12,
        GRAVEL = 13,
        OAK_LOG = 17,
        OAK_LEAVES = 18,
        GLASS = 20,
        SANDSTONE = 24,
        WOOL = 35,
        GOLD_BLOCK = 41,
        IRON_BLOCK = 42,
        BRICKS = 45,
        BOOKSHELF = 47,
        MOSSY_COBBLESTONE = 48,
        OBSIDIAN = 49,
        DIAMOND_BLOCK = 57,
        CRAFTING_TABLE = 58,
        FURNACE = 61,
        LADDER = 65,
        SNOW = 78,
        ICE = 79,
        CACTUS = 81,
        CLAY = 82,
        FENCE = 85,
        DEEPSLATE = 1000,
        TUFF = 1001,
        CALCITE = 1002,
        AMETHYST_BLOCK = 1003,
        COPPER_BLOCK = 1004,
        CHERRY_LOG = 1005,
        CHERRY_LEAVES = 1006,
        MANGROVE_LOG = 1007,
        MUD = 1008,
        SCULK = 1009,
        REINFORCED_DEEPSLATE = 1010,
    };

    struct BlockProps {
        float hardness;
        float resistance;
        bool transparent;
        bool solid;
        bool flammable;
        bool gravity;
        bool unbreakable;
        float slipperiness;
        int light_emission;
    };

    static inline std::unordered_map<int, BlockProps> get_block_properties() {
        std::unordered_map<int, BlockProps> m;
        m[AIR] = {0.0f, 0.0f, true, false, false, false, false, 0.6f, 0};
        m[STONE] = {1.5f, 6.0f, false, true, false, false, false, 0.6f, 0};
        m[GRASS_BLOCK] = {0.6f, 0.6f, false, true, false, false, false, 0.6f, 0};
        m[DIRT] = {0.5f, 0.5f, false, true, false, false, false, 0.6f, 0};
        m[COBBLESTONE] = {2.0f, 6.0f, false, true, false, false, false, 0.6f, 0};
        m[OAK_PLANKS] = {2.0f, 3.0f, false, true, true, false, false, 0.6f, 0};
        m[BEDROCK] = {-1.0f, 3600000.0f, false, true, false, false, true, 0.6f, 0};
        m[SAND] = {0.5f, 0.5f, false, true, false, true, false, 0.6f, 0};
        m[GRAVEL] = {0.6f, 0.6f, false, true, false, true, false, 0.6f, 0};
        m[OAK_LOG] = {2.0f, 2.0f, false, true, true, false, false, 0.6f, 0};
        m[OAK_LEAVES] = {0.2f, 0.2f, true, false, true, false, false, 0.6f, 0};
        m[GLASS] = {0.3f, 0.3f, true, false, false, false, false, 0.6f, 0};
        m[BRICKS] = {2.0f, 6.0f, false, true, false, false, false, 0.6f, 0};
        m[OBSIDIAN] = {50.0f, 1200.0f, false, true, false, false, false, 0.6f, 0};
        m[ICE] = {0.5f, 0.5f, true, false, false, false, false, 0.98f, 0};
        m[DEEPSLATE] = {3.0f, 6.0f, false, true, false, false, false, 0.6f, 0};
        m[TUFF] = {1.5f, 6.0f, false, true, false, false, false, 0.6f, 0};
        m[REINFORCED_DEEPSLATE] = {55.0f, 1200.0f, false, true, false, false, false, 0.6f, 0};
        return m;
    }
};

struct WorldGenConstants {
    static constexpr int SEA_LEVEL = 62;
    static constexpr int MIN_Y = -64;
    static constexpr int MAX_Y = 320;
    static constexpr int HEIGHT = 384;
    static constexpr int CHUNK_SIZE = 16;
    static constexpr int BIOME_SIZE = 4;
    static constexpr double NOISE_SCALE = 0.08;
    static constexpr int ORE_VEIN_COAL = 17;
    static constexpr int ORE_VEIN_IRON = 9;
    static constexpr int ORE_VEIN_GOLD = 9;
    static constexpr int ORE_VEIN_DIAMOND = 8;
};

struct EaglercraftConstants {
    static constexpr const char* VERSION = "26.2-0.6";
    static constexpr const char* MINECRAFT_VERSION = "26.2";
    static constexpr int PROTOCOL = 775;
    static constexpr const char* TEAVM_VERSION = "0.9.2";
    static constexpr const char* ORIGINAL_FILE = "eaglercraft-26.2-0.6.html";
    static constexpr int ORIGINAL_FILE_SIZE = 75576620;
    static constexpr const char* ORIGINAL_HASH = "07c8eefe17b88a0887493b844720c696c5bbc33038accea249d04b7ae3b70be0";
};

} // namespace Eaglercraft26
